2021-05-01 23:01:30.714401: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2021-05-01 23:01:30.714513: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2021-05-01 23:01:30.714528: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "base.py", line 283, in <module>
    execute_exp(args)
  File "base.py", line 223, in execute_exp
    ins_val, mask, outs_val, weights = load_files_from_dir(args.dataset + '/train/' + fold, filt='-[12345]9')
  File "/home/mcmontalbano/homework7/chesapeake_data.py", line 113, in load_files_from_dir
    return load_file_set(file_base, files)
  File "/home/mcmontalbano/homework7/chesapeake_data.py", line 75, in load_file_set
    sh = ins_all[0].shape
IndexError: list index out of range
